### ISSUE TITLE
Unable to change go2rtc port.

### ISSUE THREAD

**Issue by XeKToReX** [kurim/p1stream-ha#3]
Nice addon!

When attempting to change the go2rtc WebUI port it doesn't seem to apply.

I'm running Frigate NVR also and p1stream-ha isn't able to use port 1984 as frigate has it in use, so it's unable to bind.

**Comment by kurim** [comment]
Yes your right the ports are set in the dockerfile.

# Expose necessary ports
EXPOSE 8554
EXPOSE 1984

Need to check how to modify it that the changed port will be applied, but basically the UI is not needed.

**Comment by kurim** [comment]
Should be fixed with https://github.com/kurim/p1stream-ha/commit/15e0f89d4cbc0cb1e0327d213a782026f3d0996c
