### ISSUE TITLE
Webrtc videocard not working anymore

### ISSUE THREAD

**Issue by qwasy** [kurim/p1stream-ha#4]
Since the last update to 1.0.2, my Videocard stoped working.
I'm using https://github.com/AlexxIT/WebRTC to display a video card. 
(creating a generic camera in home assistant doesn't work for me, since I always get a timeout)

My card looks like this:
```
type: custom:webrtc-camera
url: rtsp://p1stream:p1stream@192.168.1.4:8554/p1s
muted: true
poster: http://p1stream:p1stream@192.168.1.4:1984/api/frame.jpeg?src=p1s
media: video
```
And I get the following error from it:
```
401, message='Invaild response status', url=URL(ws://localhost:1984/api/ws?src=rtsp://p1stream:p1stream@192.168.1.4:8554/p1s')
```

I'm using the addon with default values. Changing the port makes no difference.
Opening the rtsp url in VLC works fine, as well as in the addon itself.
I'm also open to use a different method of displaying the video.

**Comment by kurim** [comment]
Hi,

for homeassistant don't use Generic Camera use mjpeg camera
![image](https://github.com/kurim/p1stream-ha/assets/1880220/b50d25ea-411a-4de7-9fd8-491047f28ed0)
![image](https://github.com/kurim/p1stream-ha/assets/1880220/637df064-88c0-4fc4-8558-0241c483d774)

For rebroadcasting i use: Scrypted which works fine

But I also get it work.
![image](https://github.com/kurim/p1stream-ha/assets/1880220/b6f0bfa9-6bf5-46a4-92cf-f4c14e02ec54)


Set:
p1stream addon to: 1985 & 8556 to avoid issues.

Set your card like this:
```
type: custom:webrtc-camera
url: rtsp://p1stream:p1stream@localhost:8556/p1s
muted: true
poster: http://p1stream:p1stream@localhost:1985/api/stream.mjpeg?src=p1s
media: video
```

maybe you need first enable web2rtc cam and then the addon

**Comment by qwasy** [comment]
MJPEG Camera is working, jayyyy

I still get an error with WebRTC, this time `Cannot connect to host localhost:1984 ssl:default [Connect call failed ('127.0.0.1', 1984)]` even though I changed the ports to 1985....
Weird, because it worked before...
But since I got a working solution, thanks to you, I will ignore it^^

You could maybe put your setup on the main page, for others to see?

**Comment by kurim** [comment]
good suggestion, i have add it to readme.
