### ISSUE TITLE
Docker File Sharing

### ISSUE THREAD

**Issue by lunDreame** [kurim/p1stream-ha#5]
I'm making HA add-ons based on your p1stream-ha add-on so that I can upscale my P1 series camera through AI function. Dockerfile should just write your add-on image as is https://github.com/kurim/P1Stream/blob/main/ha/Dockerfile
Is that the image you used for p1stream-ha add-on? First of all, I pushed it to HA add-on, but I got an image format error, so can you share the docker image file if it's wrong?

**Comment by kurim** [comment]
No not anymore,...
Sadly i have a data loose :( so the basic part is gone, need to check if i have an not 100% up to date version

Edit:
your lucky i can reconstruct the whole files.
[p1.zip](https://github.com/kurim/p1stream-ha/files/13942548/p1.zip)

**Comment by lunDreame** [comment]
env: can't execute 'bashio
': No such file or directory

humm..... 
I modified the path to run.sh bashio to "#!/usr/bin bashio" because it was an error, but the same error occurred. The original code is "#!/usr/bin/env bashio" but I can't see the ../env folder in the HomeAsist root folder.

**Comment by kurim** [comment]
bashio is part of the build image:

https://github.com/hassio-addons/bashio
Used in:
https://github.com/hassio-addons/addon-base-python

homeassistant/amd64-base-python:latest AS base-amd64
