### ISSUE TITLE
Authorization error

### ISSUE THREAD

**Issue by Domme2000** [kurim/p1stream-ha#6]
I installed the add-on by directly adding this github repo in homeassistant. I can access the api/config page of p1stream in homeassistant and also open the stream(s) successfully.
When I try to add the MJPEG camera as described in the README.md with http://localhost:1984/api/stream.mjpeg?src=p1s or http://localhost:8554/api/stream.mjpeg?src=p1s , I get an unavailable error.

<img width="390" alt="Bildschirmfoto 2024-01-24 um 19 21 43" src="https://github.com/kurim/p1stream-ha/assets/157061742/5689c9a2-e17c-4ca3-9f58-21d00d47facb"><img width="389" alt="Bildschirmfoto 2024-01-24 um 19 22 01" src="https://github.com/kurim/p1stream-ha/assets/157061742/795f0da5-eca5-4b17-a3eb-d7b430dfb78c">

The MJPEG links, that the api/config page lists, successfully work in a new tab in the same browser, where I am logged in into homeassistant. When I try to add the camera with one of those MJPEG links, I get an 401 Unauthorized error. If I add username and password as basic auth to the URL (http://p1stream:p1stream@localhost.....) that error remains. 
If I try that link (with or without username and password) in another browser (that is not logged in into homeassistant), I also get a 401 unauthorized.

<img width="387" alt="Bildschirmfoto 2024-01-24 um 19 23 02" src="https://github.com/kurim/p1stream-ha/assets/157061742/e7ec51fd-a89c-4db4-9eff-04133ade22d9">

I also tried setting a new username and password for API and RTSP access via the Config and clicking on Save&Restart. If I then try the MJEPG link with that new username and password, it's still 401 unauthorized.

I can't figure out, what I am doing wrong. Can someone please point it out to me ?

Regards,
Dominik

**Comment by kurim** [comment]
Hi Dominik,

401 caused by wrong url
![image](https://github.com/kurim/p1stream-ha/assets/1880220/de411977-7f34-4515-9f61-6a329b7ad4ba)

My current settings:
![image](https://github.com/kurim/p1stream-ha/assets/1880220/a464d8ce-4d40-42d2-b640-16d59f2b47cd)
![image](https://github.com/kurim/p1stream-ha/assets/1880220/aa626c79-4f74-4ab5-a133-4996625e3151)

Can you show me the addon config?

Also you can try ffmpeg (ffplay) to play the stream on your pc to check if it push to the network

![image](https://github.com/kurim/p1stream-ha/assets/1880220/ee4ecd83-6b2f-49f7-89ba-a2b409a1a515)

**Comment by Domme2000** [comment]
Using the URL with the 1984 port (or 8554 port) results in a connection error. If I try to access from a different pc in the network (with correct IP instead of localhost of course) the 1984 and 8554 URL also results in a connection error, while the other links (taken from the links page of the add-on) work fine in the same browser, that I am looged in into homeassistant and give me a 401 unauthorized in another browser, where I am NOT logged in into homeassistant. Therefore it seems, that the homeassistant session cookie is required.

This is my add-on config (looks different from your page)

<img width="726" alt="Bildschirmfoto 2024-01-24 um 22 03 46" src="https://github.com/kurim/p1stream-ha/assets/157061742/ddda32e6-c41c-4366-83e1-c1c6a8f7e834">

This is the links page, I am talking about.

<img width="727" alt="Bildschirmfoto 2024-01-24 um 22 09 26" src="https://github.com/kurim/p1stream-ha/assets/157061742/2336c501-c2df-4606-857b-985eaf7f811e">


When trying to play the stream with ffplay from another pc in the network (homeassistant is running on a raspi) I get a protocol not found error. Is the ffmpeg install on the other pc missing something ?

![Bildschirmfoto 2024-01-24 um 22 24 31](https://github.com/kurim/p1stream-ha/assets/157061742/6893079e-a9b1-405f-b5ac-ffd98aa90301)

**Comment by Domme2000** [comment]
Using the 8554 port link on the other PC in safari gives me a more detailed error and it complains about the HTTP version.

<img width="587" alt="Bildschirmfoto 2024-01-24 um 22 31 51" src="https://github.com/kurim/p1stream-ha/assets/157061742/f51223a5-c032-450e-9a08-c098203f9f5a">

**Comment by Domme2000** [comment]
My Add-on config and protocol

<img width="1071" alt="Bildschirmfoto 2024-01-25 um 08 58 05" src="https://github.com/kurim/p1stream-ha/assets/157061742/b83cd3fe-09d8-4d32-a88b-a457c78524b8">
<img width="1074" alt="Bildschirmfoto 2024-01-25 um 08 58 13" src="https://github.com/kurim/p1stream-ha/assets/157061742/bf996f6f-1833-494c-9184-8c063304f78f">
<img width="1063" alt="Bildschirmfoto 2024-01-25 um 08 58 22" src="https://github.com/kurim/p1stream-ha/assets/157061742/31cad1c3-0404-462e-bd8b-8b8f5d0b85c8">

**Comment by kurim** [comment]
Can you also expose Port 1984, by click on "Deaktivierte Ports anzeigen"?
![image](https://github.com/kurim/p1stream-ha/assets/1880220/05150031-ddbe-411b-bbf3-089310370b88)

About ffplay, your url is not set correct it is:
ffplay -fflags nobuffer -flags low_delay -rtsp_transport tcp "rstp://p1stream:p1stream@192.168.178.35:8554/p1s"
Notice connecting this way take very long,...
You can check it by using the info option:
![image](https://github.com/kurim/p1stream-ha/assets/1880220/c1b78094-c504-4031-b1d0-c1bab8e3bc74)

**Comment by Domme2000** [comment]
I noticed my mistake in the ffplay command later yesterday and added the username and password and then updated the screenshot in my post later. See updated screenshot above.
It errors with "Protocol not found"
When I open that same link in Safari, I get an error regarding the http version 0.9 (see screenshot above)

I will try to expose port 1984 this evening, when I am back home.

Regards

**Comment by Domme2000** [comment]
Exposing port 1984 solved it and I could add a new MJPEG camera entity and also use that URL from another pc without homeassistant session cookie and access the stream after providing username and password.

The newly added camera entity is showing inactive when added to a dashboard though.

I will investigate further and try to find my problem. Thank you very much for your help.

**Comment by Domme2000** [comment]
Closed

**Comment by Domme2000** [comment]
Closed
